name: "Read Gist File"
description: "Returns contents of selected file from selected gist"
inputs:
  gist_id:
    description: "id of the gist"
    required: true
  file_name:
    description: "name of the file you want to get"

outputs:
  content:
    description: "file contents from the gist"

runs:
  using: "node16"
  main: "dist/index.js"
